# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170529_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
