# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170529_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tname',
        ),
    ]
