# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170529_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='tname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
