# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170529_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag', to_field='tname'),
        ),
    ]
