# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170529_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='pinyin',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
