# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_artical_pinyin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='pinyin',
        ),
    ]
