# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_artical_pinyin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, unique=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='artical',
            name='category',
            field=models.ForeignKey(db_column='category', default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', to_field='cname'),
        ),
    ]
